name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mpaiement:latest microservice-paiement/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mproduits:latest microservice-produits/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mcommandes:latest microservice-commandes/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/config-server:latest config-server/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/apollo-server:latest ApolloServer/

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mproduits:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mcommandes:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mpaiement:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/config-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/apollo-server:latest
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure Kong
      run:
        

    - name: Deploy to K8s
      run: |
        chmod +x ./apply.sh
        ./apply.sh